import { StyleSheet } from "react-native";
import { appColors, appFonts, fontSizes, windowHeight } from "@src/themes";

const MARKER_WIDTH = windowHeight(40);
const MARKER_HEIGHT = windowHeight(40);

const styles = StyleSheet.create({
  backView: {
    borderRadius: windowHeight(7),
    alignItems: "center",
    justifyContent: "center",
    height: windowHeight(36),
    width: windowHeight(36),
    position: "absolute",
    zIndex: 10,
    left: windowHeight(15),
    top: windowHeight(15),
    elevation: 5,
    shadowColor: appColors.blackColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  textInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: windowHeight(8),
    elevation: 5,
    shadowColor: appColors.blackColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  searchContainer: {
    position: "absolute",
    top: windowHeight(15),
    right: windowHeight(15),
    left: windowHeight(15),
    zIndex: 10,
  },
  currentAddressHint: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: windowHeight(8),
    marginTop: windowHeight(8),
    paddingHorizontal: windowHeight(12),
    paddingVertical: windowHeight(10),
    elevation: 4,
    shadowColor: appColors.blackColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 2,
    gap: 8,
  },
  currentAddressText: {
    flex: 1,
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.medium,
  },
  clearSearchBtn: {
    paddingHorizontal: windowHeight(10),
    paddingVertical: windowHeight(6),
  },
  suggestionContainer: {
    marginTop: windowHeight(8),
    borderRadius: windowHeight(8),
    elevation: 8,
    shadowColor: appColors.blackColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    maxHeight: windowHeight(340),
    overflow: "hidden",
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: windowHeight(12),
    paddingVertical: windowHeight(10),
    borderBottomWidth: 1,
    borderBottomColor: appColors.lightGray,
    gap: 10,
  },
  suggestionIcon: {
    width: windowHeight(30),
    height: windowHeight(30),
    borderRadius: windowHeight(15),
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionBody: {
    flex: 1,
  },
  suggestionShort: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.semiBold,
  },
  suggestionDetail: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.regular,
    color: appColors.gray,
    marginTop: 2,
  },
  suggestionDistance: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.medium,
    color: appColors.primary,
  },
  textInput: {
    flex: 1,
    fontSize: fontSizes.FONT15,
    fontFamily: appFonts.medium,
  },
  pointerMarker: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: MARKER_WIDTH,
    height: MARKER_HEIGHT,
    transform: [
      { translateX: -(MARKER_WIDTH / 2) },
      { translateY: -MARKER_HEIGHT },
    ],
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  confirmButton: {
    backgroundColor: appColors.primary,
    position: "absolute",
    height: windowHeight(56),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: windowHeight(12),
    bottom: windowHeight(24),
    right: windowHeight(20),
    left: windowHeight(20),
    zIndex: 10,
    elevation: 8,
    shadowColor: appColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  confirmText: {
    color: appColors.whiteColor,
    fontFamily: appFonts.bold,
    fontSize: 18,
    letterSpacing: 0.5,
  },
  confirmButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pinImage: {
    width: windowHeight(27),
    height: windowHeight(27),
    resizeMode: "contain",
  },
  addressBtnView: {
    width: windowHeight(40),
    height: windowHeight(40),
    borderRadius: windowHeight(8),
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: windowHeight(10),
    marginVertical: windowHeight(10),
  },
  mapView: {
    flex: 1,
    height: "100%",
  },
  loaderContainer: {
    flex: 1,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;
