SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `countries`;

ALTER TABLE `countries` CHANGE `currency_symbol` `currency_symbol` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
INSERT INTO `countries` (`id`, `name`, `currency`, `currency_symbol`, `iso_3166_2`, `iso_3166_3`, `calling_code`, `flag`, `currency_code`) VALUES
(4, 'Afghanistan', 'afghani', '؋', 'AF', 'AFG', '93', 'AF.png', 'AFN'),
(8, 'Albania', 'lek', 'L', 'AL', 'ALB', '355', 'AL.png', 'ALL'),
(10, 'Antarctica', '', '', 'AQ', 'ATA', '672', 'AQ.png', ''),
(12, 'Algeria', 'Algerian dinar', 'د.ج', 'DZ', 'DZA', '213', 'DZ.png', 'DZD'),
(16, 'American Samoa', 'US dollar', '$', 'AS', 'ASM', '1', 'AS.png', 'USD'),
(20, 'Andorra', 'euro', '€', 'AD', 'AND', '376', 'AD.png', 'EUR'),
(24, 'Angola', 'kwanza', 'Kz', 'AO', 'AGO', '244', 'AO.png', 'AOA'),
(28, 'Antigua and Barbuda', 'East Caribbean dollar', '$', 'AG', 'ATG', '1', 'AG.png', 'XCD'),
(31, 'Azerbaijan', 'Azerbaijani manat', '₼', 'AZ', 'AZE', '994', 'AZ.png', 'AZN'),
(32, 'Argentina', 'Argentine peso', '$', 'AR', 'ARG', '54', 'AR.png', 'ARS'),
(36, 'Australia', 'Australian dollar', '$', 'AU', 'AUS', '61', 'AU.png', 'AUD'),
(40, 'Austria', 'euro', '€', 'AT', 'AUT', '43', 'AT.png', 'EUR'),
(44, 'Bahamas', 'Bahamian dollar', '$', 'BS', 'BHS', '1', 'BS.png', 'BSD'),
(48, 'Bahrain', 'Bahraini dinar', '.د.ب', 'BH', 'BHR', '973', 'BH.png', 'BHD'),
(50, 'Bangladesh', 'taka (inv.)', '৳', 'BD', 'BGD', '880', 'BD.png', 'BDT'),
(51, 'Armenia', 'dram (inv.)', '֏', 'AM', 'ARM', '374', 'AM.png', 'AMD'),
(52, 'Barbados', 'Barbados dollar', '$', 'BB', 'BRB', '1', 'BB.png', 'BBD'),
(56, 'Belgium', 'euro', '€', 'BE', 'BEL', '32', 'BE.png', 'EUR'),
(60, 'Bermuda', 'Bermuda dollar', '$', 'BM', 'BMU', '1', 'BM.png', 'BMD'),
(64, 'Bhutan', 'ngultrum (inv.)', 'Nu.', 'BT', 'BTN', '975', 'BT.png', 'BTN'),
(68, 'Bolivia, Plurinational State of', 'boliviano', 'Bs.', 'BO', 'BOL', '591', 'BO.png', 'BOB'),
(70, 'Bosnia and Herzegovina', 'convertible mark', 'KM', 'BA', 'BIH', '387', 'BA.png', 'BAM'),
(72, 'Botswana', 'pula (inv.)', 'P', 'BW', 'BWA', '267', 'BW.png', 'BWP'),
(74, 'Bouvet Island', '', 'kr', 'BV', 'BVT', '47', 'BV.png', ''),
(76, 'Brazil', 'real (pl. reais)', 'R$', 'BR', 'BRA', '55', 'BR.png', 'BRL'),
(84, 'Belize', 'Belize dollar', '$', 'BZ', 'BLZ', '501', 'BZ.png', 'BZD'),
(86, 'British Indian Ocean Territory', 'US dollar', '$', 'IO', 'IOT', '246', 'IO.png', 'USD'),
(90, 'Solomon Islands', 'Solomon Islands dollar', '$', 'SB', 'SLB', '677', 'SB.png', 'SBD'),
(92, 'Virgin Islands, British', 'US dollar', '$', 'VG', 'VGB', '1', 'VG.png', 'USD'),
(96, 'Brunei Darussalam', 'Brunei dollar', '$', 'BN', 'BRN', '673', 'BN.png', 'BND'),
(100, 'Bulgaria', 'lev (pl. leva)', 'лв', 'BG', 'BGR', '359', 'BG.png', 'BGN'),
(104, 'Myanmar', 'kyat', 'K', 'MM', 'MMR', '95', 'MM.png', 'MMK'),
(108, 'Burundi', 'Burundi franc', 'Fr', 'BI', 'BDI', '257', 'BI.png', 'BIF'),
(112, 'Belarus', 'Belarusian rouble', 'Br', 'BY', 'BLR', '375', 'BY.png', 'BYN'),
(116, 'Cambodia', 'riel', '៛', 'KH', 'KHM', '855', 'KH.png', 'KHR'),
(120, 'Cameroon', 'CFA franc (BEAC)', 'Fr', 'CM', 'CMR', '237', 'CM.png', 'XAF'),
(124, 'Canada', 'Canadian dollar', '$', 'CA', 'CAN', '1', 'CA.png', 'CAD'),
(132, 'Cape Verde', 'Cape Verde escudo', '$', 'CV', 'CPV', '238', 'CV.png', 'CVE'),
(136, 'Cayman Islands', 'Cayman Islands dollar', '$', 'KY', 'CYM', '1', 'KY.png', 'KYD'),
(140, 'Central African Republic', 'CFA franc (BEAC)', 'Fr', 'CF', 'CAF', '236', 'CF.png', 'XAF'),
(144, 'Sri Lanka', 'Sri Lankan rupee', 'Rs', 'LK', 'LKA', '94', 'LK.png', 'LKR'),
(148, 'Chad', 'CFA franc (BEAC)', 'Fr', 'TD', 'TCD', '235', 'TD.png', 'XAF'),
(152, 'Chile', 'Chilean peso', '$', 'CL', 'CHL', '56', 'CL.png', 'CLP'),
(156, 'China', 'renminbi-yuan (inv.)', '¥', 'CN', 'CHN', '86', 'CN.png', 'CNY'),
(158, 'Taiwan, Province of China', 'new Taiwan dollar', 'NT$', 'TW', 'TWN', '886', 'TW.png', 'TWD'),
(162, 'Christmas Island', 'Australian dollar', '$', 'CX', 'CXR', '61', 'CX.png', 'AUD'),
(166, 'Cocos (Keeling) Islands', 'Australian dollar', '$', 'CC', 'CCK', '61', 'CC.png', 'AUD'),
(170, 'Colombia', 'Colombian peso', '$', 'CO', 'COL', '57', 'CO.png', 'COP'),
(174, 'Comoros', 'Comorian franc', 'Fr', 'KM', 'COM', '269', 'KM.png', 'KMF'),
(175, 'Mayotte', 'euro', '€', 'YT', 'MYT', '262', 'YT.png', 'EUR'),
(178, 'Congo', 'CFA franc (BEAC)', 'Fr', 'CG', 'COG', '242', 'CG.png', 'XAF'),
(180, 'Congo, the Democratic Republic of the', 'Congolese franc', 'Fr', 'CD', 'COD', '243', 'CD.png', 'CDF'),
(184, 'Cook Islands', 'New Zealand dollar', '$', 'CK', 'COK', '682', 'CK.png', 'NZD'),
(188, 'Costa Rica', 'Costa Rican colón (pl. colones)', '₡', 'CR', 'CRI', '506', 'CR.png', 'CRC'),
(191, 'Croatia', 'euro', '€', 'HR', 'HRV', '385', 'HR.png', 'EUR'),
(192, 'Cuba', 'Cuban peso', '$', 'CU', 'CUB', '53', 'CU.png', 'CUP'),
(196, 'Cyprus', 'euro', '€', 'CY', 'CYP', '357', 'CY.png', 'EUR'),
(203, 'Czechia', 'Czech koruna (pl. koruny)', 'Kč', 'CZ', 'CZE', '420', 'CZ.png', 'CZK'),
(204, 'Benin', 'CFA franc (BCEAO)', 'Fr', 'BJ', 'BEN', '229', 'BJ.png', 'XOF'),
(208, 'Denmark', 'Danish krone', 'kr', 'DK', 'DNK', '45', 'DK.png', 'DKK'),
(212, 'Dominica', 'East Caribbean dollar', '$', 'DM', 'DMA', '1', 'DM.png', 'XCD'),
(214, 'Dominican Republic', 'Dominican peso', 'RD$', 'DO', 'DOM', '1', 'DO.png', 'DOP'),
(218, 'Ecuador', 'US dollar', '$', 'EC', 'ECU', '593', 'EC.png', 'USD'),
(222, 'El Salvador', 'US dollar', '$', 'SV', 'SLV', '503', 'SV.png', 'USD'),
(226, 'Equatorial Guinea', 'CFA franc (BEAC)', 'Fr', 'GQ', 'GNQ', '240', 'GQ.png', 'XAF'),
(231, 'Ethiopia', 'birr (inv.)', 'Br', 'ET', 'ETH', '251', 'ET.png', 'ETB'),
(232, 'Eritrea', 'nakfa', 'Nfk', 'ER', 'ERI', '291', 'ER.png', 'ERN'),
(233, 'Estonia', 'euro', '€', 'EE', 'EST', '372', 'EE.png', 'EUR'),
(234, 'Faroe Islands', 'Danish krone', 'kr', 'FO', 'FRO', '298', 'FO.png', 'DKK'),
(238, 'Falkland Islands (Malvinas)', 'Falkland Islands pound', '£', 'FK', 'FLK', '500', 'FK.png', 'FKP'),
(239, 'South Georgia and the South Sandwich Islands', '', '£', 'GS', 'SGS', '44', 'GS.png', ''),
(242, 'Fiji', 'Fiji dollar', '$', 'FJ', 'FJI', '679', 'FJ.png', 'FJD'),
(246, 'Finland', 'euro', '€', 'FI', 'FIN', '358', 'FI.png', 'EUR'),
(248, 'Åland Islands', 'euro', '€', 'AX', 'ALA', '358', 'default.png', 'EUR'),
(250, 'France', 'euro', '€', 'FR', 'FRA', '33', 'FR.png', 'EUR'),
(254, 'French Guiana', 'euro', '€', 'GF', 'GUF', '594', 'GF.png', 'EUR'),
(258, 'French Polynesia', 'CFP franc', '₣', 'PF', 'PYF', '689', 'PF.png', 'XPF'),
(260, 'French Southern Territories', 'euro', '€', 'TF', 'ATF', '33', 'TF.png', 'EUR'),
(262, 'Djibouti', 'Djibouti franc', 'Fr', 'DJ', 'DJI', '253', 'DJ.png', 'DJF'),
(266, 'Gabon', 'CFA franc (BEAC)', 'Fr', 'GA', 'GAB', '241', 'GA.png', 'XAF'),
(268, 'Georgia', 'lari', '₾', 'GE', 'GEO', '995', 'GE.png', 'GEL'),
(270, 'Gambia', 'dalasi (inv.)', 'D', 'GM', 'GMB', '220', 'GM.png', 'GMD'),
(275, 'Palestine', NULL, '₪', 'PS', 'PSE', '970', 'PS.png', 'ILS'),
(276, 'Germany', 'euro', '€', 'DE', 'DEU', '49', 'DE.png', 'EUR'),
(288, 'Ghana', 'Ghana cedi', '₵', 'GH', 'GHA', '233', 'GH.png', 'GHS'),
(292, 'Gibraltar', 'Gibraltar pound', '£', 'GI', 'GIB', '350', 'GI.png', 'GIP'),
(296, 'Kiribati', 'Australian dollar', '$', 'KI', 'KIR', '686', 'KI.png', 'AUD'),
(300, 'Greece', 'euro', '€', 'GR', 'GRC', '30', 'GR.png', 'EUR'),
(304, 'Greenland', 'Danish krone', 'kr', 'GL', 'GRL', '299', 'GL.png', 'DKK'),
(308, 'Grenada', 'East Caribbean dollar', '$', 'GD', 'GRD', '1', 'GD.png', 'XCD'),
(312, 'Guadeloupe', 'euro', '€', 'GP', 'GLP', '590', 'GP.png', 'EUR'),
(316, 'Guam', 'US dollar', '$', 'GU', 'GUM', '1', 'GU.png', 'USD'),
(320, 'Guatemala', 'quetzal (pl. quetzales)', 'Q', 'GT', 'GTM', '502', 'GT.png', 'GTQ'),
(324, 'Guinea', 'Guinean franc', 'Fr', 'GN', 'GIN', '224', 'GN.png', 'GNF'),
(328, 'Guyana', 'Guyana dollar', '$', 'GY', 'GUY', '592', 'GY.png', 'GYD'),
(332, 'Haiti', 'gourde', 'G', 'HT', 'HTI', '509', 'HT.png', 'HTG'),
(334, 'Heard Island and McDonald Islands', '', '$', 'HM', 'HMD', '61', 'HM.png', ''),
(336, 'Holy See (Vatican City State)', 'euro', '€', 'VA', 'VAT', '39', 'VA.png', 'EUR'),
(340, 'Honduras', 'lempira', 'L', 'HN', 'HND', '504', 'HN.png', 'HNL'),
(344, 'Hong Kong', 'Hong Kong dollar', '$', 'HK', 'HKG', '852', 'HK.png', 'HKD'),
(348, 'Hungary', 'forint (inv.)', 'Ft', 'HU', 'HUN', '36', 'HU.png', 'HUF'),
(352, 'Iceland', 'króna (pl. krónur)', 'kr', 'IS', 'ISL', '354', 'IS.png', 'ISK'),
(356, 'India', 'Indian rupee', '₹', 'IN', 'IND', '91', 'IN.png', 'INR'),
(360, 'Indonesia', 'Indonesian rupiah (inv.)', 'Rp', 'ID', 'IDN', '62', 'ID.png', 'IDR'),
(364, 'Iran, Islamic Republic of', 'Iranian rial', '﷼', 'IR', 'IRN', '98', 'IR.png', 'IRR'),
(368, 'Iraq', 'Iraqi dinar', 'ع.د', 'IQ', 'IRQ', '964', 'IQ.png', 'IQD'),
(372, 'Ireland', 'euro', '€', 'IE', 'IRL', '353', 'IE.png', 'EUR'),
(376, 'Israel', 'shekel', '₪', 'IL', 'ISR', '972', 'IL.png', 'ILS'),
(380, 'Italy', 'euro', '€', 'IT', 'ITA', '39', 'IT.png', 'EUR'),
(384, 'Côte dIvoire', 'CFA franc (BCEAO)', 'Fr', 'CI', 'CIV', '225', 'CI.png', 'XOF'),
(388, 'Jamaica', 'Jamaica dollar', '$', 'JM', 'JAM', '1', 'JM.png', 'JMD'),
(392, 'Japan', 'yen (inv.)', '¥', 'JP', 'JPN', '81', 'JP.png', 'JPY'),
(398, 'Kazakhstan', 'tenge (inv.)', '₸', 'KZ', 'KAZ', '7', 'KZ.png', 'KZT'),
(400, 'Jordan', 'Jordanian dinar', 'د.ا', 'JO', 'JOR', '962', 'JO.png', 'JOD'),
(404, 'Kenya', 'Kenyan shilling', 'Sh', 'KE', 'KEN', '254', 'KE.png', 'KES'),
(408, 'Korea, Democratic Peoples Republic of', 'North Korean won (inv.)', '₩', 'KP', 'PRK', '850', 'KP.png', 'KPW'),
(410, 'Korea, Republic of', 'South Korean won (inv.)', '₩', 'KR', 'KOR', '82', 'KR.png', 'KRW'),
(414, 'Kuwait', 'Kuwaiti dinar', 'د.ك', 'KW', 'KWT', '965', 'KW.png', 'KWD'),
(417, 'Kyrgyzstan', 'som', 'с', 'KG', 'KGZ', '996', 'KG.png', 'KGS'),
(418, 'Lao Peoples Democratic Republic', 'kip (inv.)', '₭', 'LA', 'LAO', '856', 'LA.png', 'LAK'),
(422, 'Lebanon', 'Lebanese pound', 'ل.ل', 'LB', 'LBN', '961', 'LB.png', 'LBP'),
(426, 'Lesotho', 'loti (pl. maloti)', 'L', 'LS', 'LSO', '266', 'LS.png', 'LSL'),
(428, 'Latvia', 'euro', '€', 'LV', 'LVA', '371', 'LV.png', 'EUR'),
(430, 'Liberia', 'Liberian dollar', '$', 'LR', 'LBR', '231', 'LR.png', 'LRD'),
(434, 'Libya', 'Libyan dinar', 'ل.د', 'LY', 'LBY', '218', 'LY.png', 'LYD'),
(438, 'Liechtenstein', 'Swiss franc', 'CHF', 'LI', 'LIE', '423', 'LI.png', 'CHF'),
(440, 'Lithuania', 'euro', '€', 'LT', 'LTU', '370', 'LT.png', 'EUR'),
(442, 'Luxembourg', 'euro', '€', 'LU', 'LUX', '352', 'LU.png', 'EUR'),
(446, 'Macao', 'pataca', 'MOP$', 'MO', 'MAC', '853', 'MO.png', 'MOP'),
(450, 'Madagascar', 'ariary', 'Ar', 'MG', 'MDG', '261', 'MG.png', 'MGA'),
(454, 'Malawi', 'Malawian kwacha (inv.)', 'MK', 'MW', 'MWI', '265', 'MW.png', 'MWK'),
(458, 'Malaysia', 'ringgit (inv.)', 'RM', 'MY', 'MYS', '60', 'MY.png', 'MYR'),
(462, 'Maldives', 'rufiyaa', 'ރ.', 'MV', 'MDV', '960', 'MV.png', 'MVR'),
(466, 'Mali', 'CFA franc (BCEAO)', 'Fr', 'ML', 'MLI', '223', 'ML.png', 'XOF'),
(470, 'Malta', 'euro', '€', 'MT', 'MLT', '356', 'MT.png', 'EUR'),
(474, 'Martinique', 'euro', '€', 'MQ', 'MTQ', '596', 'MQ.png', 'EUR'),
(478, 'Mauritania', 'ouguiya', 'UM', 'MR', 'MRT', '222', 'MR.png', 'MRU'),
(480, 'Mauritius', 'Mauritian rupee', '₨', 'MU', 'MUS', '230', 'MU.png', 'MUR'),
(484, 'Mexico', 'Mexican peso', '$', 'MX', 'MEX', '52', 'MX.png', 'MXN'),
(492, 'Monaco', 'euro', '€', 'MC', 'MCO', '377', 'MC.png', 'EUR'),
(496, 'Mongolia', 'tugrik', '₮', 'MN', 'MNG', '976', 'MN.png', 'MNT'),
(498, 'Moldova, Republic of', 'Moldovan leu (pl. lei)', 'L', 'MD', 'MDA', '373', 'MD.png', 'MDL'),
(499, 'Montenegro', 'euro', '€', 'ME', 'MNE', '382', 'ME.png', 'EUR'),
(500, 'Montserrat', 'East Caribbean dollar', '$', 'MS', 'MSR', '1', 'MS.png', 'XCD'),
(504, 'Morocco', 'Moroccan dirham', 'د.م.', 'MA', 'MAR', '212', 'MA.png', 'MAD'),
(508, 'Mozambique', 'metical', 'MT', 'MZ', 'MOZ', '258', 'MZ.png', 'MZN'),
(512, 'Oman', 'Omani rial', 'ر.ع.', 'OM', 'OMN', '968', 'OM.png', 'OMR'),
(516, 'Namibia', 'Namibian dollar', '$', 'NA', 'NAM', '264', 'NA.png', 'NAD'),
(520, 'Nauru', 'Australian dollar', '$', 'NR', 'NRU', '674', 'NR.png', 'AUD'),
(524, 'Nepal', 'Nepalese rupee', '₨', 'NP', 'NPL', '977', 'NP.png', 'NPR'),
(528, 'Netherlands', 'euro', '€', 'NL', 'NLD', '31', 'NL.png', 'EUR'),
(531, 'Curaçao', 'Netherlands Antillean guilder', 'ƒ', 'CW', 'CUW', '599', 'default.png', 'ANG'),
(533, 'Aruba', 'Aruban guilder', 'ƒ', 'AW', 'ABW', '297', 'AW.png', 'AWG'),
(534, 'Sint Maarten (Dutch part)', 'Netherlands Antillean guilder', 'ƒ', 'SX', 'SXM', '721', 'default.png', 'ANG'),
(535, 'Bonaire, Sint Eustatius and Saba', 'US dollar', '$', 'BQ', 'BES', '599', 'default.png', 'USD'),
(540, 'New Caledonia', 'CFP franc', '₣', 'NC', 'NCL', '687', 'NC.png', 'XPF'),
(548, 'Vanuatu', 'vatu (inv.)', 'Vt', 'VU', 'VUT', '678', 'VU.png', 'VUV'),
(554, 'New Zealand', 'New Zealand dollar', '$', 'NZ', 'NZL', '64', 'NZ.png', 'NZD'),
(558, 'Nicaragua', 'córdoba oro', 'C$', 'NI', 'NIC', '505', 'NI.png', 'NIO'),
(562, 'Niger', 'CFA franc (BCEAO)', 'Fr', 'NE', 'NER', '227', 'NE.png', 'XOF'),
(566, 'Nigeria', 'naira (inv.)', '₦', 'NG', 'NGA', '234', 'NG.png', 'NGN'),
(570, 'Niue', 'New Zealand dollar', '$', 'NU', 'NIU', '683', 'NU.png', 'NZD'),
(574, 'Norfolk Island', 'Australian dollar', '$', 'NF', 'NFK', '672', 'NF.png', 'AUD'),
(578, 'Norway', 'Norwegian krone (pl. kroner)', 'kr', 'NO', 'NOR', '47', 'NO.png', 'NOK'),
(580, 'Northern Mariana Islands', 'US dollar', '$', 'MP', 'MNP', '1', 'MP.png', 'USD'),
(581, 'United States Minor Outlying Islands', 'US dollar', '$', 'UM', 'UMI', '1', 'UM.png', 'USD'),
(583, 'Micronesia, Federated States of', 'US dollar', '$', 'FM', 'FSM', '691', 'FM.png', 'USD'),
(584, 'Marshall Islands', 'US dollar', '$', 'MH', 'MHL', '692', 'MH.png', 'USD'),
(585, 'Palau', 'US dollar', '$', 'PW', 'PLW', '680', 'PW.png', 'USD'),
(586, 'Pakistan', 'Pakistani rupee', '₨', 'PK', 'PAK', '92', 'PK.png', 'PKR'),
(591, 'Panama', 'balboa', 'B/.', 'PA', 'PAN', '507', 'PA.png', 'PAB'),
(598, 'Papua New Guinea', 'kina (inv.)', 'K', 'PG', 'PNG', '675', 'PG.png', 'PGK'),
(600, 'Paraguay', 'guaraní', '₲', 'PY', 'PRY', '595', 'PY.png', 'PYG'),
(604, 'Peru', 'new sol', 'S/.', 'PE', 'PER', '51', 'PE.png', 'PEN'),
(608, 'Philippines', 'Philippine peso', '₱', 'PH', 'PHL', '63', 'PH.png', 'PHP'),
(612, 'Pitcairn', 'New Zealand dollar', '$', 'PN', 'PCN', '649', 'PN.png', 'NZD'),
(616, 'Poland', 'zloty', 'zł', 'PL', 'POL', '48', 'PL.png', 'PLN'),
(620, 'Portugal', 'euro', '€', 'PT', 'PRT', '351', 'PT.png', 'EUR'),
(624, 'Guinea-Bissau', 'CFA franc (BCEAO)', 'Fr', 'GW', 'GNB', '245', 'GW.png', 'XOF'),
(626, 'Timor-Leste', 'US dollar', '$', 'TL', 'TLS', '670', 'TL.png', 'USD'),
(630, 'Puerto Rico', 'US dollar', '$', 'PR', 'PRI', '1', 'PR.png', 'USD'),
(634, 'Qatar', 'Qatari riyal', 'ر.ق', 'QA', 'QAT', '974', 'QA.png', 'QAR'),
(638, 'Réunion', 'euro', '€', 'RE', 'REU', '262', 'RE.png', 'EUR'),
(642, 'Romania', 'Romanian leu (pl. lei)', 'lei', 'RO', 'ROU', '40', 'RO.png', 'RON'),
(643, 'Russian Federation', 'Russian rouble', '₽', 'RU', 'RUS', '7', 'RU.png', 'RUB'),
(646, 'Rwanda', 'Rwandese franc', 'Fr', 'RW', 'RWA', '250', 'RW.png', 'RWF'),
(652, 'Saint Barthélemy', 'euro', '€', 'BL', 'BLM', '590', 'default.png', 'EUR'),
(654, 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena pound', '£', 'SH', 'SHN', '290', 'SH.png', 'SHP'),
(659, 'Saint Kitts and Nevis', 'East Caribbean dollar', '$', 'KN', 'KNA', '1', 'KN.png', 'XCD'),
(660, 'Anguilla', 'East Caribbean dollar', '$', 'AI', 'AIA', '1', 'AI.png', 'XCD'),
(662, 'Saint Lucia', 'East Caribbean dollar', '$', 'LC', 'LCA', '1', 'LC.png', 'XCD'),
(663, 'Saint Martin (French part)', 'euro', '€', 'MF', 'MAF', '590', 'default.png', 'EUR'),
(666, 'Saint Pierre and Miquelon', 'euro', '€', 'PM', 'SPM', '508', 'PM.png', 'EUR'),
(670, 'Saint Vincent and the Grenadines', 'East Caribbean dollar', '$', 'VC', 'VCT', '1', 'VC.png', 'XCD'),
(674, 'San Marino', 'euro', '€', 'SM', 'SMR', '378', 'SM.png', 'EUR'),
(678, 'Sao Tome and Principe', 'dobra', 'Db', 'ST', 'STP', '239', 'ST.png', 'STN'),
(682, 'Saudi Arabia', 'riyal', 'ر.س', 'SA', 'SAU', '966', 'SA.png', 'SAR'),
(686, 'Senegal', 'CFA franc (BCEAO)', 'Fr', 'SN', 'SEN', '221', 'SN.png', 'XOF'),
(688, 'Serbia', 'Serbian dinar', 'дин', 'RS', 'SRB', '381', 'default.png', 'RSD'),
(690, 'Seychelles', 'Seychelles rupee', '₨', 'SC', 'SYC', '248', 'SC.png', 'SCR'),
(694, 'Sierra Leone', 'leone', 'Le', 'SL', 'SLE', '232', 'SL.png', 'SLE'),
(702, 'Singapore', 'Singapore dollar', '$', 'SG', 'SGP', '65', 'SG.png', 'SGD'),
(703, 'Slovakia', 'euro', '€', 'SK', 'SVK', '421', 'SK.png', 'EUR'),
(704, 'Viet Nam', 'dong', '₫', 'VN', 'VNM', '84', 'VN.png', 'VND'),
(705, 'Slovenia', 'euro', '€', 'SI', 'SVN', '386', 'SI.png', 'EUR'),
(706, 'Somalia', 'Somali shilling', 'Sh', 'SO', 'SOM', '252', 'SO.png', 'SOS'),
(710, 'South Africa', 'rand', 'R', 'ZA', 'ZAF', '27', 'ZA.png', 'ZAR'),
(716, 'Zimbabwe', 'Zimbabwe Gold', 'Z$', 'ZW', 'ZWE', '263', 'ZW.png', 'ZWG'),
(724, 'Spain', 'euro', '€', 'ES', 'ESP', '34', 'ES.png', 'EUR'),
(728, 'South Sudan', 'South Sudanese pound', '£', 'SS', 'SSD', '211', 'default.png', 'SSP'),
(729, 'Sudan', 'Sudanese pound', 'ج.س.', 'SD', 'SDN', '249', 'default.png', 'SDG'),
(732, 'Western Sahara', 'Moroccan dirham', 'د.م.', 'EH', 'ESH', '212', 'EH.png', 'MAD'),
(740, 'Suriname', 'Surinamese dollar', '$', 'SR', 'SUR', '597', 'SR.png', 'SRD'),
(744, 'Svalbard and Jan Mayen', 'Norwegian krone (pl. kroner)', 'kr', 'SJ', 'SJM', '47', 'SJ.png', 'NOK'),
(748, 'Eswatini', 'lilangeni', 'E', 'SZ', 'SWZ', '268', 'SZ.png', 'SZL'),
(752, 'Sweden', 'krona (pl. kronor)', 'kr', 'SE', 'SWE', '46', 'SE.png', 'SEK'),
(756, 'Switzerland', 'Swiss franc', 'CHF', 'CH', 'CHE', '41', 'CH.png', 'CHF'),
(760, 'Syrian Arab Republic', 'Syrian pound', 'ل.س', 'SY', 'SYR', '963', 'SY.png', 'SYP'),
(762, 'Tajikistan', 'somoni', 'ЅМ', 'TJ', 'TJK', '992', 'TJ.png', 'TJS'),
(764, 'Thailand', 'baht (inv.)', '฿', 'TH', 'THA', '66', 'TH.png', 'THB'),
(768, 'Togo', 'CFA franc (BCEAO)', 'Fr', 'TG', 'TGO', '228', 'TG.png', 'XOF'),
(772, 'Tokelau', 'New Zealand dollar', '$', 'TK', 'TKL', '690', 'TK.png', 'NZD'),
(776, 'Tonga', 'pa’anga (inv.)', 'T$', 'TO', 'TON', '676', 'TO.png', 'TOP'),
(780, 'Trinidad and Tobago', 'Trinidad and Tobago dollar', '$', 'TT', 'TTO', '1', 'TT.png', 'TTD'),
(784, 'United Arab Emirates', 'UAE dirham', 'د.إ', 'AE', 'ARE', '971', 'AE.png', 'AED'),
(788, 'Tunisia', 'Tunisian dinar', 'د.ت', 'TN', 'TUN', '216', 'TN.png', 'TND'),
(792, 'Turkey', 'Turkish lira (inv.)', '₺', 'TR', 'TUR', '90', 'TR.png', 'TRY'),
(795, 'Turkmenistan', 'Turkmen manat (inv.)', 'm', 'TM', 'TKM', '993', 'TM.png', 'TMT'),
(796, 'Turks and Caicos Islands', 'US dollar', '$', 'TC', 'TCA', '1', 'TC.png', 'USD'),
(798, 'Tuvalu', 'Australian dollar', '$', 'TV', 'TUV', '688', 'TV.png', 'AUD'),
(800, 'Uganda', 'Uganda shilling', 'Sh', 'UG', 'UGA', '256', 'UG.png', 'UGX'),
(804, 'Ukraine', 'hryvnia', '₴', 'UA', 'UKR', '380', 'UA.png', 'UAH'),
(807, 'North Macedonia', 'denar (pl. denars)', 'ден', 'MK', 'MKD', '389', 'MK.png', 'MKD'),
(818, 'Egypt', 'Egyptian pound', '£', 'EG', 'EGY', '20', 'EG.png', 'EGP'),
(826, 'United Kingdom', 'pound sterling', '£', 'GB', 'GBR', '44', 'GB.png', 'GBP'),
(831, 'Guernsey', 'Guernsey pound', '£', 'GG', 'GGY', '44', 'default.png', 'GGP'),
(832, 'Jersey', 'Jersey pound', '£', 'JE', 'JEY', '44', 'default.png', 'JEP'),
(833, 'Isle of Man', 'Manx pound', '£', 'IM', 'IMN', '44', 'default.png', 'IMP'),
(834, 'Tanzania, United Republic of', 'Tanzanian shilling', 'Sh', 'TZ', 'TZA', '255', 'TZ.png', 'TZS'),
(840, 'United States', 'US dollar', '$', 'US', 'USA', '1', 'US.png', 'USD'),
(850, 'Virgin Islands, U.S.', 'US dollar', '$', 'VI', 'VIR', '1', 'VI.png', 'USD'),
(854, 'Burkina Faso', 'CFA franc (BCEAO)', 'Fr', 'BF', 'BFA', '226', 'BF.png', 'XOF'),
(858, 'Uruguay', 'Uruguayan peso', '$', 'UY', 'URY', '598', 'UY.png', 'UYU'),
(860, 'Uzbekistan', 'sum (inv.)', 'лв', 'UZ', 'UZB', '998', 'UZ.png', 'UZS'),
(862, 'Venezuela, Bolivarian Republic of', 'bolívar digital', 'Bs.', 'VE', 'VEN', '58', 'VE.png', 'VED'),
(876, 'Wallis and Futuna', 'CFP franc', '₣', 'WF', 'WLF', '681', 'WF.png', 'XPF'),
(882, 'Samoa', 'tala (inv.)', 'T', 'WS', 'WSM', '685', 'WS.png', 'WST'),
(887, 'Yemen', 'Yemeni rial', '﷼', 'YE', 'YEM', '967', 'YE.png', 'YER'),
(894, 'Zambia', 'Zambian kwacha (inv.)', 'ZK', 'ZM', 'ZMB', '260', 'ZM.png', 'ZMW');

UPDATE `menu_items` SET `label` = CASE `id`
    WHEN 1  THEN 'sidebar.dashboard'
    WHEN 2  THEN 'sidebar.users'
    WHEN 3  THEN 'sidebar.all_users'
    WHEN 4  THEN 'sidebar.add_user'
    WHEN 5  THEN 'sidebar.role_permissions'
    WHEN 6  THEN 'sidebar.media'
    WHEN 7  THEN 'sidebar.blogs'
    WHEN 8  THEN 'sidebar.all_blogs'
    WHEN 9  THEN 'sidebar.add_blogs'
    WHEN 10 THEN 'sidebar.categories'
    WHEN 11 THEN 'sidebar.tags'
    WHEN 12 THEN 'sidebar.pages'
    WHEN 13 THEN 'sidebar.all_pages'
    WHEN 14 THEN 'sidebar.add_page'
    WHEN 15 THEN 'sidebar.notify_templates'
    WHEN 16 THEN 'sidebar.email_templates'
    WHEN 17 THEN 'sidebar.sms_templates'
    WHEN 18 THEN 'sidebar.push_notification_templates'
    WHEN 19 THEN 'sidebar.testimonials'
    WHEN 20 THEN 'sidebar.all_testimonials'
    WHEN 21 THEN 'sidebar.add_testimonial'
    WHEN 22 THEN 'sidebar.faqs'
    WHEN 23 THEN 'sidebar.general_settings'
    WHEN 24 THEN 'sidebar.languages'
    WHEN 25 THEN 'sidebar.taxes'
    WHEN 26 THEN 'sidebar.currencies'
    WHEN 27 THEN 'sidebar.plugins'
    WHEN 28 THEN 'sidebar.payment_methods'
    WHEN 29 THEN 'sidebar.sms_gateways'
    WHEN 30 THEN 'sidebar.about_system'
    WHEN 31 THEN 'sidebar.settings'
    WHEN 32 THEN 'sidebar.appearance'
    WHEN 33 THEN 'sidebar.robots'
    WHEN 34 THEN 'sidebar.landing_page'
    WHEN 35 THEN 'sidebar.subscribers'
    WHEN 36 THEN 'sidebar.customizations'
    WHEN 37 THEN 'sidebar.system_tools'
    WHEN 38 THEN 'sidebar.backup'
    WHEN 39 THEN 'sidebar.activity_logs'
    WHEN 40 THEN 'sidebar.database_cleanup'
    WHEN 41 THEN 'sidebar.menus'
END
WHERE `id` BETWEEN 1 AND 41;
