import { StyleSheet } from "react-native";
import {
  appColors,
  appFonts,
  fontSizes,
  windowHeight,
  windowWidth,
} from "@src/themes";

const styles = StyleSheet.create({
  main: { flex: 1, backgroundColor: appColors.whiteColor },
  headerMain: {
    paddingHorizontal: windowWidth(20),
    paddingVertical: windowHeight(10),
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  width: {
    width: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  headerIcon: {
    width: windowWidth(44),
    height: windowWidth(44),
    borderRadius: windowWidth(8),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: appColors.border,
    backgroundColor: appColors.whiteColor,
  },
  headerTitle: {
    fontSize: fontSizes.FONT22,
    fontFamily: appFonts.semiBold,
    color: appColors.primaryText,
  },
  headerRightIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  targetIconView: {
    backgroundColor: appColors.lightGreen,
    borderColor: appColors.lightGreen,
    marginRight: windowWidth(10),
  },
  bookmarkIconView: {
    backgroundColor: appColors.primary,
    borderColor: appColors.primary,
  },
  horizontalView: {
    paddingHorizontal: windowWidth(20),
  },
  pickupdetailsView: {
    marginTop: windowHeight(15),
  },
  containers: {
    borderWidth: 1,
    paddingHorizontal: windowWidth(15),
    paddingVertical: windowHeight(0),
    borderRadius: windowWidth(12),
    backgroundColor: appColors.lightGray,
    position: "relative",
    height: windowHeight(76),
    justifyContent: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: windowHeight(30),
  },
  input: {
    flex: 1,
    height: "100%",
    color: appColors.primaryText,
    fontFamily: appFonts.medium,
    marginHorizontal: windowWidth(10),
    fontSize: fontSizes.FONT16,
    padding: 0,
  },
  divider: {
    height: 1,
    backgroundColor: appColors.border,
    marginVertical: windowHeight(5),
    marginLeft: windowWidth(30),
  },
  dotLineContainer: {
    position: "absolute",
    left: windowWidth(15),
    top: windowHeight(10),
    bottom: windowHeight(13),
    alignItems: "center",
    width: 20,
    zIndex: 1,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: appColors.primary,
  },
  dashedLine: {
    flex: 1,
    width: 1,
    borderWidth: 1,
    borderColor: appColors.iconColor,
    borderStyle: "dashed",
    marginVertical: 5,
  },
  dateTimeCard: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: windowWidth(12),
    backgroundColor: appColors.whiteColor,
    marginTop: windowHeight(15),
    paddingVertical: windowHeight(7),
  },
  dateTimeItem: {
    flex: 1,
    paddingHorizontal: windowWidth(15),
  },
  verticalDivider: {
    width: 1,
    borderWidth: 1,
    borderColor: appColors.border,
    height: "100%",
    borderStyle: "dashed",
  },
  label: {
    fontSize: fontSizes.FONT16,
    color: appColors.primaryText,
    fontFamily: appFonts.semiBold,
  },
  valueContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: windowHeight(5),
  },
  valueText: {
    fontSize: fontSizes.FONT14,
    color: appColors.regularText,
    fontFamily: appFonts.medium,
    marginLeft: windowWidth(8),
  },
  gearTypeLabel: {
    marginTop: windowHeight(10),
    marginBottom: windowHeight(8),
    fontSize: fontSizes.FONT18,
    fontFamily: appFonts.semiBold,
    color: appColors.primaryText,
  },
  gearOptionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  gearOption: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: windowWidth(9),
    paddingVertical: windowHeight(9),
    paddingHorizontal: windowWidth(15),
    width: "48%",
    backgroundColor: appColors.whiteColor,
  },
  selectedGearOption: {
    borderColor: appColors.primary,
  },
  gearOptionText: {
    marginLeft: windowWidth(10),
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.medium,
    color: appColors.primaryText,
  },
  recentView: {
    backgroundColor: appColors.notificationColor,
    paddingHorizontal: windowWidth(20),
    paddingTop: windowHeight(8),
    marginTop: windowHeight(20),
    paddingBottom: windowHeight(20),
    flex: 1,
  },
  recentLabel: {
    fontSize: fontSizes.FONT20,
    fontFamily: appFonts.semiBold,
    color: appColors.primaryText,
    marginBottom: windowHeight(8),
  },
  recentCardContainer: {
    backgroundColor: appColors.whiteColor,
    borderRadius: windowWidth(12),
    borderWidth: windowWidth(0.45),
    borderColor: appColors.border,
  },
  historyBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: windowHeight(12),
    paddingHorizontal: windowWidth(15),
  },
  historyIconContainer: {
    width: windowWidth(40),
    height: windowWidth(40),
    borderRadius: windowWidth(22),
    backgroundColor: appColors.lightGray,
    alignItems: "center",
    justifyContent: "center",
  },
  historyIconContainerActive: {
    backgroundColor: appColors.lightGray,
  },
  recentItemContent: {
    marginLeft: windowWidth(15),
    flex: 1,
  },
  recentItemTitle: {
    fontSize: fontSizes.FONT18,
    fontFamily: appFonts.semiBold,
    color: appColors.primaryText,
  },
  recentItemAddress: {
    fontSize: fontSizes.FONT13,
    color: appColors.regularText,
    fontFamily: appFonts.regular,
    marginTop: 2,
  },
  recentItemDivider: {
    height: 1,
    backgroundColor: appColors.border,
    marginVertical: windowHeight(1),
  },
  suggestionsCard: {
    backgroundColor: appColors.whiteColor,
    borderRadius: windowWidth(12),
    paddingVertical: windowWidth(10),
    marginBottom: windowHeight(20),
  },
  suggestionsView: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: windowHeight(8),
    paddingHorizontal: windowWidth(15),
  },
  titleText: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.bold,
    color: appColors.primaryText,
  },
  titleTextDetail: {
    fontSize: fontSizes.FONT13,
    color: appColors.regularText,
    fontFamily: appFonts.regular,
  },
  noAddressText: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.regular,
    color: appColors.regularText,
    textAlign: "center",
    marginTop: windowHeight(18),
  },
  addressItemView: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: windowHeight(50),
  },
  modalContent: {
    padding: windowWidth(20),
    paddingBottom: windowHeight(30),
    paddingTop: windowHeight(1),
    paddingHorizontal: windowWidth(5),
  },
  modalHandle: {
    width: windowWidth(50),
    height: 4,
    backgroundColor: appColors.primary,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: windowHeight(20),
  },
  modalTitle: {
    fontSize: fontSizes.FONT18,
    fontFamily: appFonts.medium,
    color: appColors.primaryText,
    marginBottom: windowHeight(10),
  },
  selectedDateTimeText: {
    fontSize: fontSizes.FONT22,
    fontFamily: appFonts.bold,
    color: appColors.primary,
    marginBottom: windowHeight(20),
  },
  pickerHeaderRow: {
    flexDirection: "row",
    marginBottom: windowHeight(15),
    zIndex: 5000,
  },
  pickerDropdown: {
    borderColor: appColors.border,
    borderRadius: 8,
    height: 40,
  },
  pickerDropdownContainer: {
    borderColor: appColors.border,
  },
  timePickerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: windowHeight(20),
    paddingHorizontal: windowWidth(10),
  },
  timePickerBox: {
    alignItems: "center",
    borderWidth: 1,
    borderColor: appColors.border,
    borderRadius: 8,
    paddingVertical: 10,
    width: "30%",
  },
  timePickerText: {
    fontSize: fontSizes.FONT20,
    fontFamily: appFonts.bold,
    color: appColors.primary,
    marginVertical: 5,
  },
  distanceText: {
    fontSize: fontSizes.FONT15,
    fontFamily: appFonts.bold,
    color: appColors.primary,
  },
});

export { styles };
